site_name: DIY Stazione Meteo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: it
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passa alla modalità chiara
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Passa alla modalità scura
      primary: teal
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xShader1374/DIY-Stazione-Meteo

copyright: |
  &copy; 2024-2024 <a href="https://github.com/xShader1374/DIY-Stazione-Meteo" target="_blank" rel="noopener">xShader1374, etome, giovi_ama, JLouisS, dspreafico, Dada</a>