site_name: DIY Stazione Meteo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - content.tooltips
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - header.autohide


  language: it
  
  font:
    text: Roboto
    code: Roboto Mono
    
  icon:
    repo: fontawesome/brands/github-alt
    
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Passa alla modalità chiara
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Passa alla modalità scura

plugins:
  - search
  - tags
  - git-revision-date-localized:
      type: datetime
      locale: it
  - glightbox:
      effect: zoom
      
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xShader1374/DIY-Stazione-Meteo

repo_url: https://github.com/xShader1374/DIY-Stazione-Meteo
repo_name: xShader1374/DIY-Stazione-Meteo
edit_uri: edit/main/docs/